apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - name: influxdb
      port: 8181
      targetPort: 8181
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      nodeSelector:
        role: database
      containers:
        - image: influxdb:3-core
          name: influxdb
          ports:
            - containerPort: 8181
              name: influxdb
          volumeMounts:
            - name: influxdb-persistent-storage
              mountPath: /var/lib/influxdb3/data
          command: ["influxdb3"]
          args:
            - serve
            - --node-id=node0
            - --object-store=file
            - --data-dir=/var/lib/influxdb3/data
            - --plugin-dir=/var/lib/influxdb3/plugins
          securityContext:
            runAsUser: 0
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
