# This is purely for local testing

services:
  test_db:
    container_name: test_db
    image: influxdb:3-core
    ports:
      - 8182:8181
    command:
      - influxdb3
      - serve
      - --without-auth
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - influxdb-test-data:/var/lib/influxdb3/data
    user: "0"
  test_broker:
    restart: unless-stopped
    container_name: test_broker
    image: eclipse-mosquitto
    ports:
      - 1884:1883
    command: >
      sh -c "echo 'listener 1883 0.0.0.0' > /tmp/mosquitto.conf && echo 'allow_anonymous true' >> /tmp/mosquitto.conf && mosquitto -c /tmp/mosquitto.conf -v"
volumes:
  influxdb-test-data:
