apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      nodeSelector:
        role: broker
      containers:
        - image: eclipse-mosquitto
          name: mosquitto
          ports:
            - containerPort: 1883
              name: mosquitto
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config
            - name: log
              mountPath: /mosquitto/log
      volumes:
        - name: config
          hostPath:
            path: /mnt/mosquitto/config
        - name: log
          hostPath:
            path: /mnt/mosquitto/log
