apiVersion: v1
kind: Pod
metadata:
  name: subscriber-test
spec:
  containers:
    - name: subscriber
      image: ghcr.io/lukaalhonen/bananafarm-sim:subscriber-latest
      imagePullPolicy: IfNotPresent
      env:
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: db-token
              key: db_token
        - name: DB_ADDRESS
          value: "http://influxdb.default.svc.cluster.local:8181/api/v3/write_lp?db=bananafarm"
        - name: TABLE
          value: "soil_moisture_readings"
        - name: TOPIC
          value: "bananafarm/soil_moisture"
        - name: BROKER_ADDRESS
          value: "mosquitto"
        - name: BROKER_PORT
          value: "1883"
  nodeSelector:
    role: subscriber
